cargo-features = ["edition2024"]

[package]
name = "tmcg"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-primes = "0.5.0"
crypto-bigint = "0.5.5"
num-integer = "0.1.46"
num-traits = "0.2.18"
serde = { version = "1.0.210", features = ["derive"] }
